languageCode = "en-us"
title = "rain-or-shine"
description = "rain-or-shine is a weather app for Strava"
assetDir = "assets"

[params]
subtitle = "Add weather information to Strava activities"

[[params.javascript]]
  link = "js/script.js"
  id = "script"

[[params.javascript]]
  link = "js/cookeinfo.js"
  id = "cookieinfo"

[[params.css]]
  link = "css/style.css"

[params.strava]
  oauth_url =       "https://www.strava.com/oauth/authorize"
  cid =             "PLACEHOLDER_STRAVA_API_CLIENT_ID"
  redirectbaseurl = "http://localhost:8888"
  redirect_path =   "/connect/callback/"
  response_type =   "code"
  approval_prompt = "auto"
  scope =           "read,activity:write,activity:read"
  state =           "not_used"

[params.pages]
  connect = "/connect/"
  settings =  "/settings/"
