[build]
  functions = "./functions"
  publish = "public"
  command = "yarn build"

[build.environment]
  HUGO_VERSION = "0.62.2"
  YARN_VERSION = "1.22.4"

[dev]
  command = "yarn start"
  autoLaunch = true
